### ISSUE TITLE
K2P可以在线更新passwall，16M剩余空间不够

### ISSUE THREAD

**Issue by 142857X1** [Chikage0o0/Openwrt-AIO#2]
可以硬改32M的闪存么？可以的话应该选啥颗粒有要求么？

**Comment by Chikage0o0** [comment]
16m用xray的话理论上空间是完全足够的，硬改后需要你自己适配硬件

**Comment by 142857X1** [comment]
> 16m用xray的话理论上空间是完全足够的，硬改后需要你自己适配硬件

只升级闪存和内存的话 还要适配么?自己识别不出来?

**Comment by Chikage0o0** [comment]
> > 16m用xray的话理论上空间是完全足够的，硬改后需要你自己适配硬件
> 
> 只升级闪存和内存的话 还要适配么?自己识别不出来?

内存不需要适配，闪存需要
